=== BogdanCerovac/a11ysupport.io/data/schema/dev-test.json
{
  "$id": "http://accessibilitysupported.com/dev-test.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "at_version": {
      "type": "object",
      "properties": {
        "browsers": {
          "type": "object",
          "properties": {
            "chrome": {
              "$ref": "#/definitions/browser_version"
            },
            "and_chr": {
              "$ref": "#/definitions/browser_version"
            },
            "edge": {
              "$ref": "#/definitions/browser_version"
            },
            "firefox": {
              "$ref": "#/definitions/browser_version"
            },
            "and_ff": {
              "$ref": "#/definitions/browser_version"
            },
            "ie": {
              "$ref": "#/definitions/browser_version"
            },
            "ios_saf": {
              "$ref": "#/definitions/browser_version"
            },
            "safari": {
              "$ref": "#/definitions/browser_version"
            }
          }
        }
      },
      "required": ["browsers"]
    },
    "browser_version": {
      "type": "object",
      "properties": {
        "at_version": {
          "type": "string"
        },
        "browser_version": {
          "type": "string"
        },
        "os_version": {
          "type": "string",
          "description": "The OS version indicates what accessibility APIs are in use"
        },
        "date": {
          "description": "The date is required to help us determine which support points have priority for testing.",
          "type": "string",
          "format": "date"
        }
      },
      "required": ["at_version", "browser_version", "os_version", "date"]
    },
    "at": {
      "type": "object",
      "properties": {
        "browsers": {
          "type": "object",
          "properties": {
            "chrome": {
              "$ref": "#/definitions/browser"
            },
            "and_chr": {
              "$ref": "#/definitions/browser"
            },
            "edge": {
              "$ref": "#/definitions/browser"
            },
            "firefox": {
              "$ref": "#/definitions/browser"
            },
            "and_ff": {
              "$ref": "#/definitions/browser"
            },
            "ie": {
              "$ref": "#/definitions/browser"
            },
            "ios_saf": {
              "$ref": "#/definitions/browser"
            },
            "safari": {
              "$ref": "#/definitions/browser"
            }
          }
        }
      },
      "required": ["browsers"]
    },
    "browser": {
      "type": "object",
      "properties": {
        "support": {
          "description": "Is the combination supported? y=yes, p=partial, n=no, na=not-applicable. If partial, please provide extra documentation as to why.",
          "type": "string",
          "enum": ["y", "p", "n", "na", "u"]
        },
        "output": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "command": {
                "description": "The id of the keyboard command. It MUST be a property name in the relevant ATBrowsers.results[at].commands object",
                "type": "string"
              },
              "from": {
                "type": "string",
                "enum": ["before target", "after target", "target", "within target", "start of target", "end of target", "na"],
                "description": "Describes the focus/cursor destination before the command."
              },
              "to": {
                "type": "string",
                "enum": ["target", "start of target", "end of target", "past target", "before target", "within target", "after target", "na"],
                "description": "Describes the focus/cursor destination after the command."
              },
              "output": {
                "type": "string"
              },
              "result": {
                "type": "string",
                "enum": ["pass", "fail", "partial", "unknown", "na"]
              },
              "behind_setting": {
                "type": "string",
                "description": "If support is hidden behind a non-default setting, describe that setting here."
              }
            },
            "required": ["command", "result"]
          }
        },
        "notes": {
          "description": "Any relevant notes. This can be in markdown format.",
          "type": "string"
        }
      },
      "required": ["output"]
    },
    "assertion": {
      "type": "object",
      "properties": {
        "feature_id": {
          "type": "string"
        },
        "feature_assertion_id": {
          "type": "string"
        },
        "css_target": {
          "type": "string",
          "description": "A css selector that determines which elements in the example need to be tested."
        },
        "expected_value": {
          "type": "string",
          "description": "an example of expected output; does not need to be exact. This can be helpful especially for things like computed accessible names and descriptions."
        },
        "results": {
          "type": "object",
          "properties": {
            "jaws": {
              "$ref": "#/definitions/at"
            },
            "nvda": {
              "$ref": "#/definitions/at"
            },
            "vo_ios": {
              "$ref": "#/definitions/at"
            },
            "vo_macos": {
              "$ref": "#/definitions/at"
            },
            "narrator": {
              "$ref": "#/definitions/at"
            },
            "android": {
              "$ref": "#/definitions/at"
            },
            "dragon_win": {
              "$ref": "#/definitions/at"
            }
          }
        }
      },
      "required": ["feature_id", "feature_assertion_id", "results"]
    },
    "history": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string",
          "format": "date"
        },
        "message": {
          "type": "string"
        }
      },
      "required": ["date", "message"]
    }
  },
  "properties": {
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "keywords": {
      "description": "Key words that are used to help find features in a search",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "html_file": {
      "type": "string",
      "description": "path relative to the /data/tests/html directory. References the file that contains the test html."
    },
    "versions": {
      "type": "object",
      "properties": {
        "jaws": {
          "$ref": "#/definitions/at_version"
        },
        "nvda": {
          "$ref": "#/definitions/at_version"
        },
        "vo_ios": {
          "$ref": "#/definitions/at_version"
        },
        "vo_macos": {
          "$ref": "#/definitions/at_version"
        },
        "narrator": {
          "$ref": "#/definitions/at_version"
        },
        "android": {
          "$ref": "#/definitions/at_version"
        },
        "dragon_win": {
          "$ref": "#/definitions/at_version"
        }
      }
    },
    "assertions": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/assertion"
      }
    },
    "history": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/history"
      }
    }
  },
  "required": [
    "title",
    "description",
    "history",
    "versions",
    "assertions"
  ]
}

=== BogdanCerovac/a11ysupport.io/data/tests/aria_roledescription_with_html_button.json
{
  "title": "aria-roledescription attribute with HTML button",
  "description": "This test ensures that the value of aria-roledescription is announced by screen readers",
  "assertions": [
    {
      "feature_id": "aria/aria-roledescription_attribute",
      "feature_assertion_id": "convey_value",
      "css_target": "#target",
      "results": {
        "jaws": {
          "browsers": {
            "chrome": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"target, custom button\"",
                  "result": "pass"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"target, custom button. To activate press space bar.\"",
                  "result": "pass"
                }
              ]
            },
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"target, custom button.\"",
                  "result": "pass"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"target, custom button. To activate press space bar.\"",
                  "result": "pass"
                }
              ]
            },
            "ie": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"target, custom button.\"",
                  "result": "pass"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"Target, custom button. To activate press space bar.\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "narrator": {
          "browsers": {
            "edge": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"custom button, target\"",
                  "result": "pass"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"Target. Custom button.\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "nvda": {
          "browsers": {
            "chrome": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"custom button, target\"",
                  "result": "pass"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"custom button, target\"",
                  "result": "pass"
                }
              ]
            },
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"custom button, target\"",
                  "result": "pass"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"Target, custom button.\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "orca": {
          "browsers": {
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"target, custom button\"",
                  "result": "pass"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"target, custom button\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "talkback": {
          "browsers": {
            "and_chr": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"target, button, double tap to activate\"",
                  "result": "fail"
                }
              ]
            }
          }
        },
        "vo_macos": {
          "browsers": {
            "safari": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"Target, custom button\"",
                  "result": "pass"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "Target, custom button",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "vo_ios": {
          "browsers": {
            "ios_saf": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "Target, custom button",
                  "result": "pass"
                }
              ]
            }
          }
        }
      }
    }
  ],
  "history": [
    {
      "date": "2019-09-09",
      "message": "Updated support info and added data for talkback and orca"
    },
    {
      "date": "2018-11-12",
      "message": "Test created"
    }
  ],
  "versions": {
    "jaws": {
      "browsers": {
        "chrome": {
          "at_version": "2019.1907.42",
          "browser_version": "76",
          "os_version": "1903",
          "date": "2019-09-09"
        },
        "firefox": {
          "at_version": "2019.1907.42",
          "browser_version": "69",
          "os_version": "1903",
          "date": "2019-09-09"
        },
        "ie": {
          "at_version": "2019.1907.42",
          "browser_version": "11",
          "os_version": "1903",
          "date": "2019-09-09"
        }
      }
    },
    "narrator": {
      "browsers": {
        "edge": {
          "at_version": "1903",
          "browser_version": "44",
          "os_version": "1903",
          "date": "2019-09-09"
        }
      }
    },
    "nvda": {
      "browsers": {
        "chrome": {
          "at_version": "2019.2",
          "browser_version": "76",
          "os_version": "1903",
          "date": "2019-09-09"
        },
        "firefox": {
          "at_version": "2019.2",
          "browser_version": "76",
          "os_version": "1903",
          "date": "2019-09-09"
        }
      }
    },
    "orca": {
      "browsers": {
        "firefox": {
          "at_version": "3.31.4",
          "browser_version": "69",
          "os_version": "Ubuntu 19.04",
          "date": "2019-09-09"
        }
      }
    },
    "talkback": {
      "browsers": {
        "and_chr": {
          "at_version": "7.3.0",
          "browser_version": "76",
          "os_version": "9",
          "date": "2019-09-09"
        }
      }
    },
    "vo_ios": {
      "browsers": {
        "ios_saf": {
          "at_version": "12.4.1",
          "browser_version": "12.4.1",
          "os_version": "12.4.1",
          "date": "2019-09-09"
        }
      }
    },
    "vo_macos": {
      "browsers": {
        "safari": {
          "at_version": "10.14.6",
          "browser_version": "12.1.2",
          "os_version": "10.14.6",
          "date": "2019-09-09"
        }
      }
    }
  }
}

=== BogdanCerovac/a11ysupport.io/data/tests/tech/aria/aria_describedby.json
{
  "title": "aria-describedby attribute on a text input",
  "description": "This test ensures that the accessible description is computed correctly when `aria-describedby` on a text input.",
  "html_file": "aria/aria_describedby.html",
  "assertions": [
    {
      "feature_id": "aria/aria-describedby_attribute",
      "feature_assertion_id": "convey_value_if_valid",
      "results": {
        "jaws": {
          "browsers": {
            "firefox": {
              "output": [
                {
                  "command": "next_focusable_item",
                  "output": "\"Example label, edit, error\"",
                  "result": "pass"
                }
              ]
            },
            "chrome": {
              "output": [
                {
                  "command": "next_focusable_item",
                  "output": "\"Example label, edit, error\"",
                  "result": "pass"
                }
              ]
            },
            "ie": {
              "output": [
                {
                  "command": "next_focusable_item",
                  "output": "\"Example label, edit, error\"",
                  "result": "pass"
                }
              ]
            },
            "edge": {
              "output": [
                {
                  "command": "next_focusable_item",
                  "output": "\"Example label, edit\"",
                  "result": "fail"
                }
              ]
            }
          }
        },
        "narrator": {
          "browsers": {
            "edge": {
              "output": [
                {
                  "command": "next_focusable_item",
                  "output": "\"Example label, editing\"",
                  "result": "fail"
                }
              ]
            }
          }
        },
        "nvda": {
          "browsers": {
            "firefox": {
              "output": [
                {
                  "command": "next_focusable_item",
                  "output": "\"Example label edit has auto complete, error\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "orca": {
          "browsers": {
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "output": "\"example label, entry\"",
                  "result": "fail"
                },
                {
                  "command": "next_focusable_item",
                  "output": "\"example label, entry, error, focus mode\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "vo_ios": {
          "browsers": {
            "ios_saf": {
              "output": [
                {
                  "command": "next_item",
                  "output": "\"Example label, edit text, error\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "vo_macos": {
          "browsers": {
            "safari": {
              "output": [
                {
                  "command": "next_item",
                  "output": "\"Example label, edit text, error\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "talkback": {
          "browsers": {
            "and_chr": {
              "output": [
                {
                  "command": "next_item",
                  "output": "\"Edit box, example label, error\"",
                  "result": "pass"
                }
              ]
            }
          }
        }
      }
    }
  ],
  "history": [
    {
      "date": "2019-07-27",
      "message": "Talkback results added"
    },
    {
      "date": "2019-02-08",
      "message": "Test created"
    },
    {
      "date": "2019-09-16",
      "message": "Add orca results"
    }
  ],
  "versions": {
    "jaws": {
      "browsers": {
        "chrome": {
          "at_version": "2018.1811.2",
          "browser_version": "72",
          "os_version": "1809",
          "date": "2019-03-08"
        },
        "ie": {
          "at_version": "2018.1811.2",
          "browser_version": "11",
          "os_version": "1809",
          "date": "2019-03-08"
        },
        "firefox": {
          "at_version": "2018.1811.2",
          "browser_version": "60",
          "os_version": "1809",
          "date": "2019-03-08"
        },
        "edge": {
          "at_version": "2018.1811.2",
          "browser_version": "44",
          "os_version": "1809",
          "date": "2019-03-08"
        }
      }
    },
    "narrator": {
      "browsers": {
        "edge": {
          "at_version": "1809",
          "browser_version": "44.17763",
          "os_version": "1809",
          "date": "2019-03-08"
        }
      }
    },
    "nvda": {
      "browsers": {
        "firefox": {
          "at_version": "2018.4.1",
          "browser_version": "65.0.2",
          "os_version": "1804",
          "date": "2019-03-08"
        }
      }
    },
    "orca": {
      "browsers": {
        "firefox": {
          "at_version": "3.31.4",
          "browser_version": "69",
          "os_version": "Ubuntu 19.04",
          "date": "2019-09-16"
        }
      }
    },
    "vo_ios": {
      "browsers": {
        "ios_saf": {
          "at_version": "12.1.4",
          "browser_version": "12.1.4",
          "os_version": "12.1.4",
          "date": "2019-03-08"
        }
      }
    },
    "vo_macos": {
      "browsers": {
        "safari": {
          "at_version": "10.14.3",
          "browser_version": "12.0.3",
          "os_version": "10.14.3",
          "date": "2019-03-08"
        }
      }
    },
    "talkback": {
      "browsers": {
        "and_chr": {
          "at_version": "7.3.0",
          "browser_version": "75",
          "os_version": "7.0",
          "date": "2019-07-27"
        }
      }
    }
  }
}

=== BogdanCerovac/a11ysupport.io/data/tests/tech/aria/role_button_name_from_inner.json
{
  "title": "ARIA button name from inner text",
  "description": "This test ensures that the accessible name is computed correctly for inner text.",
  "html_file": "aria/aria_button_examples.html",
  "assertions": [
    {
      "feature_id": "aria/button_role",
      "feature_assertion_id": "convey_accessible_name",
      "css_target": "#target_0",
      "results": {
        "dragon_win": {
          "browsers": {
            "ie": {
              "output": [
                {
                  "command": "activate_actionable_item",
                  "output": "(target was clicked)",
                  "result": "pass"
                },
                {
                  "command": "click_type",
                  "output": "(all elements of type were flagged)",
                  "result": "pass"
                }
              ]
            }
          }
        }
      }
    }
  ],
  "history": [
    {
      "date": "2019-02-08",
      "message": "Test created"
    }
  ],
  "versions": {
    "dragon_win": {
      "browsers": {
        "ie": {
          "at_version": "15.30",
          "browser_version": "11.253",
          "os_version": "1809",
          "date": "2018-11-15"
        }
      }
    }
  }
}
