=== BogdanCerovac/a11ysupport.io/data/schema/dev-test.json
{
  "$id": "http://accessibilitysupported.com/dev-test.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "at_version": {
      "type": "object",
      "properties": {
        "browsers": {
          "type": "object",
          "properties": {
            "chrome": {
              "$ref": "#/definitions/browser_version"
            },
            "and_chr": {
              "$ref": "#/definitions/browser_version"
            },
            "edge": {
              "$ref": "#/definitions/browser_version"
            },
            "firefox": {
              "$ref": "#/definitions/browser_version"
            },
            "and_ff": {
              "$ref": "#/definitions/browser_version"
            },
            "ie": {
              "$ref": "#/definitions/browser_version"
            },
            "ios_saf": {
              "$ref": "#/definitions/browser_version"
            },
            "safari": {
              "$ref": "#/definitions/browser_version"
            }
          }
        }
      },
      "required": ["browsers"]
    },
    "browser_version": {
      "type": "object",
      "properties": {
        "at_version": {
          "type": "string"
        },
        "browser_version": {
          "type": "string"
        },
        "os_version": {
          "type": "string",
          "description": "The OS version indicates what accessibility APIs are in use"
        },
        "date": {
          "description": "The date is required to help us determine which support points have priority for testing.",
          "type": "string",
          "format": "date"
        }
      },
      "required": ["at_version", "browser_version", "os_version", "date"]
    },
    "at": {
      "type": "object",
      "properties": {
        "browsers": {
          "type": "object",
          "properties": {
            "chrome": {
              "$ref": "#/definitions/browser"
            },
            "and_chr": {
              "$ref": "#/definitions/browser"
            },
            "edge": {
              "$ref": "#/definitions/browser"
            },
            "firefox": {
              "$ref": "#/definitions/browser"
            },
            "and_ff": {
              "$ref": "#/definitions/browser"
            },
            "ie": {
              "$ref": "#/definitions/browser"
            },
            "ios_saf": {
              "$ref": "#/definitions/browser"
            },
            "safari": {
              "$ref": "#/definitions/browser"
            }
          }
        }
      },
      "required": ["browsers"]
    },
    "browser": {
      "type": "object",
      "properties": {
        "support": {
          "description": "Is the combination supported? y=yes, p=partial, n=no, na=not-applicable. If partial, please provide extra documentation as to why.",
          "type": "string",
          "enum": ["y", "p", "n", "na", "u"]
        },
        "output": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "command": {
                "description": "The id of the keyboard command. It MUST be a property name in the relevant ATBrowsers.results[at].commands object",
                "type": "string"
              },
              "from": {
                "type": "string",
                "enum": ["before target", "after target", "target", "within target", "start of target", "end of target", "na"],
                "description": "Describes the focus/cursor destination before the command."
              },
              "to": {
                "type": "string",
                "enum": ["target", "start of target", "end of target", "past target", "before target", "within target", "after target", "na"],
                "description": "Describes the focus/cursor destination after the command."
              },
              "output": {
                "type": "string"
              },
              "result": {
                "type": "string",
                "enum": ["pass", "fail", "partial", "unknown", "na"]
              },
              "behind_setting": {
                "type": "string",
                "description": "If support is hidden behind a non-default setting, describe that setting here."
              }
            },
            "required": ["command", "result"]
          }
        },
        "notes": {
          "description": "Any relevant notes. This can be in markdown format.",
          "type": "string"
        }
      },
      "required": ["output"]
    },
    "assertion": {
      "type": "object",
      "properties": {
        "feature_id": {
          "type": "string"
        },
        "feature_assertion_id": {
          "type": "string"
        },
        "css_target": {
          "type": "string",
          "description": "A css selector that determines which elements in the example need to be tested."
        },
        "expected_value": {
          "type": "string",
          "description": "an example of expected output; does not need to be exact. This can be helpful especially for things like computed accessible names and descriptions."
        },
        "results": {
          "type": "object",
          "properties": {
            "jaws": {
              "$ref": "#/definitions/at"
            },
            "nvda": {
              "$ref": "#/definitions/at"
            },
            "vo_ios": {
              "$ref": "#/definitions/at"
            },
            "vo_macos": {
              "$ref": "#/definitions/at"
            },
            "narrator": {
              "$ref": "#/definitions/at"
            },
            "android": {
              "$ref": "#/definitions/at"
            },
            "dragon_win": {
              "$ref": "#/definitions/at"
            }
          }
        }
      },
      "required": ["feature_id", "feature_assertion_id", "results"]
    },
    "history": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string",
          "format": "date"
        },
        "message": {
          "type": "string"
        }
      },
      "required": ["date", "message"]
    }
  },
  "properties": {
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "keywords": {
      "description": "Key words that are used to help find features in a search",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "html_file": {
      "type": "string",
      "description": "path relative to the /data/tests/html directory. References the file that contains the test html."
    },
    "versions": {
      "type": "object",
      "properties": {
        "jaws": {
          "$ref": "#/definitions/at_version"
        },
        "nvda": {
          "$ref": "#/definitions/at_version"
        },
        "vo_ios": {
          "$ref": "#/definitions/at_version"
        },
        "vo_macos": {
          "$ref": "#/definitions/at_version"
        },
        "narrator": {
          "$ref": "#/definitions/at_version"
        },
        "android": {
          "$ref": "#/definitions/at_version"
        },
        "dragon_win": {
          "$ref": "#/definitions/at_version"
        }
      }
    },
    "assertions": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/assertion"
      }
    },
    "history": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/history"
      }
    }
  },
  "required": [
    "title",
    "description",
    "history",
    "versions",
    "assertions"
  ]
}

=== BogdanCerovac/a11ysupport.io/data/tests/aria_roledescription_with_html_section.json
{
  "title": "aria-roledescription attribute with HTML section",
  "description": "This test ensures that the value of aria-roledescription is announced by screen readers",
  "assertions": [
    {
      "feature_id": "aria/aria-roledescription_attribute",
      "feature_assertion_id": "convey_value",
      "css_target": "#target",
      "results": {
        "jaws": {
          "browsers": {
            "edge": {
              "output": [
                {
                  "command": "next_item",
                  "output": "Target",
                  "result": "fail"
                }
              ]
            },
            "ie": {
              "output": [
                {
                  "command": "next_item",
                  "output": "Target",
                  "result": "fail"
                }
              ]
            }
          }
        },
        "narrator": {
          "browsers": {
            "edge": {
              "output": [
                {
                  "command": "next_item",
                  "output": "Target",
                  "result": "fail"
                }
              ]
            }
          }
        },
        "nvda": {
          "browsers": {
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "output": "Section name custom section role. Target.",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "vo_macos": {
          "browsers": {
            "safari": {
              "output": [
                {
                  "command": "next_item",
                  "output": "Section name, custom section role",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "vo_ios": {
          "browsers": {
            "ios_saf": {
              "output": [
                {
                  "command": "next_item",
                  "output": "Target, section name, landmark",
                  "result": "fail"
                }
              ],
              "notes": ""
            }
          }
        }
      }
    }
  ],
  "history": [
    {
      "date": "2018-11-12",
      "message": "Test created"
    }
  ],
  "versions": {
    "jaws": {
      "browsers": {
        "ie": {
          "at_version": "2018.1808.10",
          "browser_version": "11.55",
          "os_version": "17763",
          "date": "2018-11-12"
        },
        "edge": {
          "at_version": "2018.1808.10",
          "browser_version": "44.17763.1.0",
          "os_version": "17763",
          "date": "2018-11-12"
        }
      }
    },
    "narrator": {
      "browsers": {
        "edge": {
          "at_version": "17763",
          "browser_version": "44.17763.1.0",
          "os_version": "17763",
          "date": "2018-11-12"
        }
      }
    },
    "nvda": {
      "browsers": {
        "firefox": {
          "at_version": "2018.3.2",
          "browser_version": "63.0.1",
          "os_version": "17763",
          "date": "2018-11-12"
        }
      }
    },
    "vo_ios": {
      "browsers": {
        "ios_saf": {
          "at_version": "12.1",
          "browser_version": "12.1",
          "os_version": "12.1",
          "date": "2018-11-12"
        }
      }
    },
    "vo_macos": {
      "browsers": {
        "safari": {
          "at_version": "10.14.1",
          "browser_version": "12.0.1",
          "os_version": "10.14.1",
          "date": "2018-10-19"
        }
      }
    }
  }
}

=== BogdanCerovac/a11ysupport.io/data/tests/css_generated_content.json
{
  "title": "CSS Generated Content with HTML span element",
  "description": "This test uses ::before and ::after pseudo classes to add content to static text",
  "assertions": [
    {
      "feature_id": "css/generated_content",
      "feature_assertion_id": "part_of_accessible_name",
      "css_target": "#target",
      "results": {
        "jaws": {
          "browsers": {
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "output": "This is generated content.",
                  "result": "pass"
                }
              ]
            },
            "ie": {
              "output": [
                {
                  "command": "next_item",
                  "output": "is generated",
                  "result": "fail"
                }
              ]
            },
            "edge": {
              "output": [
                {
                  "command": "next_item",
                  "output": "This is generated content.",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "nvda": {
          "browsers": {
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "output": "This is generated content.",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "vo_ios": {
          "browsers": {
            "ios_saf": {
              "output": [
                {
                  "command": "next_item",
                  "output": "this. is generated. content.",
                  "result": "pass"
                },
                {
                  "command": "start_reading",
                  "output": "this is generated content",
                  "result": "pass"
                }
              ],
              "notes": "When using the next/previous line command, you have to swipe left/right three times to hear the entire sentence. The first swipe right reads the before generated content 'this', the next swipe right reads the html contents 'is generated', and the final swipe right reads the after generated content 'content'."
            }
          }
        },
        "vo_macos": {
          "browsers": {
            "safari": {
              "output": [
                {
                  "command": "next_item",
                  "output": "This is generated content.",
                  "result": "pass"
                },
                {
                  "command": "start_reading",
                  "output": "This is generated content.",
                  "result": "pass"
                }
              ],
              "notes": ""
            }
          }
        },
        "narrator": {
          "browsers": {
            "edge": {
              "output": [
                {
                  "command": "next_item",
                  "output": "This is generated content.",
                  "result": "pass"
                }
              ],
              "notes": ""
            }
          }
        }
      }
    }
  ],
  "history": [
    {
      "date": "2018-07-06",
      "message": "Sample data has been added. This data has not been verified."
    },
    {
      "date": "2018-08-12",
      "message": "vo_ios/ios_saf support updated"
    },
    {
      "date": "2018-08-19",
      "message": "vo_macos/safari support updated"
    },
    {
      "date": "2018-12-17",
      "message": "narrator/edge support updated"
    },
    {
      "date": "2019-03-21",
      "message": "jaws/ie updated with latest versions"
    }
  ],
  "versions": {
    "jaws": {
      "browsers": {
        "ie": {
          "at_version": "2019.1903",
          "browser_version": "11",
          "os_version": "1809",
          "date": "2019-03-21"
        },
        "firefox": {
          "at_version": "18",
          "browser_version": "60",
          "os_version": "17134",
          "date": "2018-07-21"
        },
        "edge": {
          "at_version": "18",
          "browser_version": "17",
          "os_version": "17134",
          "date": "2018-07-21"
        }
      }
    },
    "narrator": {
      "browsers": {
        "edge": {
          "at_version": "1809",
          "browser_version": "44",
          "os_version": "1809",
          "date": "2018-12-17"
        }
      }
    },
    "nvda": {
      "browsers": {
        "firefox": {
          "at_version": "2018.1.1",
          "browser_version": "60",
          "os_version": "17134",
          "date": "2018-07-21"
        }
      }
    },
    "vo_ios": {
      "browsers": {
        "ios_saf": {
          "at_version": "11.4.1",
          "browser_version": "11.4.1",
          "os_version": "11.4.1",
          "date": "2018-08-12"
        }
      }
    },
    "vo_macos": {
      "browsers": {
        "safari": {
          "at_version": "10.13.6",
          "browser_version": "11.1.2",
          "os_version": "10.13.6",
          "date": "2018-08-19"
        }
      }
    }
  }
}

=== BogdanCerovac/a11ysupport.io/data/tests/html_li_element_in_ol_with_sub_ol_setsize.json
{
  "title": "HTML LI element in a OL with a sub OL (setsize)",
  "description": "This test ensures that the number of items in a list are being computed correctly when there is a sub-list.",
  "html_file": "html_li_element_in_ol_with_sub_ol.html",
  "assertions": [
    {
      "feature_id": "html/ol_element",
      "feature_assertion_id": "convey_setsize",
      "css_target": "#target",
      "expected_value": "3",
      "results": {
        "narrator": {
          "browsers": {
            "edge": {
              "output": [
                {
                  "command": "next_item",
                  "output": "\"Enter list. 1. Target. 1 of 3 level 1.\"",
                  "result": "pass"
                }
              ],
              "notes": ""
            }
          }
        },
        "nvda": {
          "browsers": {
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "output": "\"List with 3 items. 1. Target.\"",
                  "result": "pass"
                }
              ]
            },
            "chrome": {
              "output": [
                {
                  "command": "next_item",
                  "output": "\"List with 3 items. 1. Target.\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "jaws": {
          "browsers": {
            "ie": {
              "output": [
                {
                  "command": "next_item",
                  "output": "\"List of 3 items\"",
                  "result": "pass"
                }
              ],
              "notes": ""
            },
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "output": "\"List of 3 items\"",
                  "result": "pass"
                }
              ],
              "notes": ""
            },
            "chrome": {
              "output": [
                {
                  "command": "next_item",
                  "output": "\"List of 3 items\"",
                  "result": "pass"
                }
              ],
              "notes": ""
            }
          }
        },
        "vo_macos": {
          "browsers": {
            "safari": {
              "output": [
                {
                  "command": "next_item",
                  "output": "list. 3 items",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "vo_ios": {
          "browsers": {
            "ios_saf": {
              "output": [
                {
                  "command": "next_item",
                  "output": "Target. List Start",
                  "result": "fail"
                }
              ],
              "notes": ""
            }
          }
        }
      }
    }
  ],
  "history": [
    {
      "date": "2018-10-19",
      "message": "Test created"
    }
  ],
  "versions": {
    "jaws": {
      "browsers": {
        "chrome": {
          "at_version": "2018.1811.2",
          "browser_version": "74",
          "os_version": "1809",
          "date": "2019-05-20"
        },
        "ie": {
          "at_version": "2018.1811.2",
          "browser_version": "11.134",
          "os_version": "1809",
          "date": "2019-05-20"
        },
        "firefox": {
          "at_version": "2018.1811.2",
          "browser_version": "66",
          "os_version": "1809",
          "date": "2019-05-20"
        }
      }
    },
    "narrator": {
      "browsers": {
        "edge": {
          "at_version": "1809",
          "browser_version": "44.17763",
          "os_version": "1809",
          "date": "2019-05-20"
        }
      }
    },
    "nvda": {
      "browsers": {
        "chrome": {
          "at_version": "2018.1808.10",
          "browser_version": "74",
          "os_version": "1809",
          "date": "2019-05-20"
        },
        "firefox": {
          "at_version": "2018.3.2",
          "browser_version": "62",
          "os_version": "17763",
          "date": "2018-10-19"
        }
      }
    },
    "vo_ios": {
      "browsers": {
        "ios_saf": {
          "at_version": "12.2",
          "browser_version": "12.2",
          "os_version": "12.2",
          "date": "2019-05-20"
        }
      }
    },
    "vo_macos": {
      "browsers": {
        "safari": {
          "at_version": "10.14",
          "browser_version": "12",
          "os_version": "10.14",
          "date": "2018-10-19"
        }
      }
    }
  }
}

=== BogdanCerovac/a11ysupport.io/data/tests/aria_dialog_document_mode.json
{
  "title": "ARIA dialog role must use document mode",
  "description": "This test ensures the dialog role does not invoke application mode in screen readers. The default mode (document) must be used. [ARIA 1.0 had language for the dialog role](https://www.w3.org/TR/wai-aria-1.0/roles#dialog) that could suggest that application mode must be invoked. However, that language was [clarified in aria 1.1](https://www.w3.org/TR/wai-aria-1.1/#dialog).",
  "assertions": [
    {
      "feature_id": "aria/alert_role",
      "feature_assertion_id": "stay_in_reading_mode",
      "results": {
        "nvda": {
          "browsers": {
            "chrome": {
              "output": [
                {
                  "command": "next_item",
                  "output": "target",
                  "result": "pass"
                }
              ]
            },
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "output": "target",
                  "result": "pass"
                }
              ],
              "notes": "An element in the dialog had to receive focus before the contents of the dialog would be read by NVDA."
            }
          }
        },
        "jaws": {
          "browsers": {
            "ie": {
              "output": [
                {
                  "command": "next_item",
                  "output": "target",
                  "result": "pass"
                }
              ]
            },
            "chrome": {
              "output": [
                {
                  "command": "next_item",
                  "output": "target",
                  "result": "pass"
                }
              ]
            },
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "output": "target",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "vo_macos": {
          "browsers": {
            "safari": {
              "output": [
                {
                  "command": "next_item",
                  "output": "target",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "narrator": {
          "browsers": {
            "edge": {
              "output": [
                {
                  "command": "next_item",
                  "output": "target",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "vo_ios": {
          "browsers": {
            "ios_saf": {
              "output": [
                {
                  "command": "next_item",
                  "output": "target",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "talkback": {
          "browsers": {
            "and_chr": {
              "output": [
                {
                  "command": "next_item",
                  "output": "target",
                  "result": "pass"
                }
              ]
            }
          }
        }
      }
    }
  ],
  "history": [
    {
      "date": "2019-01-18",
      "message": "Test created"
    }
  ],
  "versions": {
    "jaws": {
      "browsers": {
        "chrome": {
          "at_version": "2018.1808.10",
          "browser_version": "74",
          "os_version": "1809",
          "date": "2019-05-19"
        },
        "ie": {
          "at_version": "2018.1811.2",
          "browser_version": "11.253",
          "os_version": "1809",
          "date": "2019-01-19"
        },
        "firefox": {
          "at_version": "2018.1811.2",
          "browser_version": "66",
          "os_version": "1809",
          "date": "2019-05-19"
        }
      }
    },
    "narrator": {
      "browsers": {
        "edge": {
          "at_version": "1809",
          "browser_version": "44.17763",
          "os_version": "1809",
          "date": "2018-01-18"
        }
      }
    },
    "nvda": {
      "browsers": {
        "chrome": {
          "at_version": "2018.1808.10",
          "browser_version": "74",
          "os_version": "1809",
          "date": "2019-05-19"
        },
        "firefox": {
          "at_version": "2018.4.1",
          "browser_version": "64.0.2",
          "os_version": "1809",
          "date": "2019-01-19"
        }
      }
    },
    "talkback": {
      "browsers": {
        "and_chr": {
          "at_version": "7.2",
          "browser_version": "67",
          "os_version": "8.1",
          "date": "2018-07-21"
        }
      }
    },
    "vo_ios": {
      "browsers": {
        "ios_saf": {
          "at_version": "12.1.2",
          "browser_version": "12.1.2",
          "os_version": "12.1.2",
          "date": "2018-01-18"
        }
      }
    },
    "vo_macos": {
      "browsers": {
        "safari": {
          "at_version": "10.14.2",
          "browser_version": "12.0.2",
          "os_version": "10.14.2",
          "date": "2018-10-26"
        }
      }
    }
  }
}
