=== BogdanCerovac/a11ysupport.io/data/schema/dev-test.json
{
  "$id": "http://accessibilitysupported.com/dev-test.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "at_version": {
      "type": "object",
      "properties": {
        "browsers": {
          "type": "object",
          "properties": {
            "chrome": {
              "$ref": "#/definitions/browser_version"
            },
            "and_chr": {
              "$ref": "#/definitions/browser_version"
            },
            "edge": {
              "$ref": "#/definitions/browser_version"
            },
            "firefox": {
              "$ref": "#/definitions/browser_version"
            },
            "and_ff": {
              "$ref": "#/definitions/browser_version"
            },
            "ie": {
              "$ref": "#/definitions/browser_version"
            },
            "ios_saf": {
              "$ref": "#/definitions/browser_version"
            },
            "safari": {
              "$ref": "#/definitions/browser_version"
            }
          }
        }
      },
      "required": ["browsers"]
    },
    "browser_version": {
      "type": "object",
      "properties": {
        "at_version": {
          "type": "string"
        },
        "browser_version": {
          "type": "string"
        },
        "os_version": {
          "type": "string",
          "description": "The OS version indicates what accessibility APIs are in use"
        },
        "date": {
          "description": "The date is required to help us determine which support points have priority for testing.",
          "type": "string",
          "format": "date"
        }
      },
      "required": ["at_version", "browser_version", "os_version", "date"]
    },
    "at": {
      "type": "object",
      "properties": {
        "browsers": {
          "type": "object",
          "properties": {
            "chrome": {
              "$ref": "#/definitions/browser"
            },
            "and_chr": {
              "$ref": "#/definitions/browser"
            },
            "edge": {
              "$ref": "#/definitions/browser"
            },
            "firefox": {
              "$ref": "#/definitions/browser"
            },
            "and_ff": {
              "$ref": "#/definitions/browser"
            },
            "ie": {
              "$ref": "#/definitions/browser"
            },
            "ios_saf": {
              "$ref": "#/definitions/browser"
            },
            "safari": {
              "$ref": "#/definitions/browser"
            }
          }
        }
      },
      "required": ["browsers"]
    },
    "browser": {
      "type": "object",
      "properties": {
        "support": {
          "description": "Is the combination supported? y=yes, p=partial, n=no, na=not-applicable. If partial, please provide extra documentation as to why.",
          "type": "string",
          "enum": ["y", "p", "n", "na", "u"]
        },
        "output": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "command": {
                "description": "The id of the keyboard command. It MUST be a property name in the relevant ATBrowsers.results[at].commands object",
                "type": "string"
              },
              "from": {
                "type": "string",
                "enum": ["before target", "after target", "target", "within target", "start of target", "end of target", "na"],
                "description": "Describes the focus/cursor destination before the command."
              },
              "to": {
                "type": "string",
                "enum": ["target", "start of target", "end of target", "past target", "before target", "within target", "after target", "na"],
                "description": "Describes the focus/cursor destination after the command."
              },
              "output": {
                "type": "string"
              },
              "result": {
                "type": "string",
                "enum": ["pass", "fail", "partial", "unknown", "na"]
              },
              "behind_setting": {
                "type": "string",
                "description": "If support is hidden behind a non-default setting, describe that setting here."
              }
            },
            "required": ["command", "result"]
          }
        },
        "notes": {
          "description": "Any relevant notes. This can be in markdown format.",
          "type": "string"
        }
      },
      "required": ["output"]
    },
    "assertion": {
      "type": "object",
      "properties": {
        "feature_id": {
          "type": "string"
        },
        "feature_assertion_id": {
          "type": "string"
        },
        "css_target": {
          "type": "string",
          "description": "A css selector that determines which elements in the example need to be tested."
        },
        "expected_value": {
          "type": "string",
          "description": "an example of expected output; does not need to be exact. This can be helpful especially for things like computed accessible names and descriptions."
        },
        "results": {
          "type": "object",
          "properties": {
            "jaws": {
              "$ref": "#/definitions/at"
            },
            "nvda": {
              "$ref": "#/definitions/at"
            },
            "vo_ios": {
              "$ref": "#/definitions/at"
            },
            "vo_macos": {
              "$ref": "#/definitions/at"
            },
            "narrator": {
              "$ref": "#/definitions/at"
            },
            "android": {
              "$ref": "#/definitions/at"
            },
            "dragon_win": {
              "$ref": "#/definitions/at"
            }
          }
        }
      },
      "required": ["feature_id", "feature_assertion_id", "results"]
    },
    "history": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string",
          "format": "date"
        },
        "message": {
          "type": "string"
        }
      },
      "required": ["date", "message"]
    }
  },
  "properties": {
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "keywords": {
      "description": "Key words that are used to help find features in a search",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "html_file": {
      "type": "string",
      "description": "path relative to the /data/tests/html directory. References the file that contains the test html."
    },
    "versions": {
      "type": "object",
      "properties": {
        "jaws": {
          "$ref": "#/definitions/at_version"
        },
        "nvda": {
          "$ref": "#/definitions/at_version"
        },
        "vo_ios": {
          "$ref": "#/definitions/at_version"
        },
        "vo_macos": {
          "$ref": "#/definitions/at_version"
        },
        "narrator": {
          "$ref": "#/definitions/at_version"
        },
        "android": {
          "$ref": "#/definitions/at_version"
        },
        "dragon_win": {
          "$ref": "#/definitions/at_version"
        }
      }
    },
    "assertions": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/assertion"
      }
    },
    "history": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/history"
      }
    }
  },
  "required": [
    "title",
    "description",
    "history",
    "versions",
    "assertions"
  ]
}

=== BogdanCerovac/a11ysupport.io/data/tests/tech/aria/aria-labelledby-one-ref.json
{
  "title": "aria-labelledby with one reference test",
  "description": "A simple aria-labelledby test that references a single ID",
  "html_file": "aria/aria-labelling.html",
  "assertions": [
    {
      "feature_id": "aria/aria-label_attribute",
      "feature_assertion_id": "contribute_to_accessible_name",
      "results": {
        "dragon_win": {
          "browsers": {
            "chrome": {
              "output": [
                {
                  "command": "activate_name",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            }
          }
        },
        "jaws": {
          "browsers": {
            "chrome": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            },
            "ie": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            },
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            }
          }
        },
        "narrator": {
          "browsers": {
            "edge": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            }
          }
        },
        "nvda": {
          "browsers": {
            "chrome": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            },
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            }
          }
        },
        "talkback": {
          "browsers": {
            "and_chr": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            }
          }
        },
        "vo_ios": {
          "browsers": {
            "ios_saf": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            }
          }
        },
        "vo_macos": {
          "browsers": {
            "safari": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            }
          }
        },
        "orca": {
          "browsers": {
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                },
                {
                  "command": "next_focusable_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            }
          }
        },
        "vc_ios": {
          "browsers": {
            "ios_saf": {
              "output": [
                {
                  "command": "activate_name",
                  "output": "\"\"",
                  "result": "unknown"
                }
              ]
            }
          }
        }
      }
    }
  ],
  "history": [
    {
      "date": "2019-09-27",
      "message": "Test created"
    }
  ],
  "versions": {
    "dragon_win": {
      "browsers": {
        "chrome": {
          "at_version": "15.30",
          "browser_version": "77",
          "os_version": "1903",
          "date": "2019-09-27"
        }
      }
    },
    "jaws": {
      "browsers": {
        "chrome": {
          "at_version": "2019.1907.42",
          "browser_version": "77",
          "os_version": "1903",
          "date": "2019-09-27"
        },
        "ie": {
          "at_version": "2019.1907.42",
          "browser_version": "11",
          "os_version": "1903",
          "date": "2019-09-27"
        },
        "firefox": {
          "at_version": "2019.1907.42",
          "browser_version": "69",
          "os_version": "1903",
          "date": "2019-09-27"
        }
      }
    },
    "narrator": {
      "browsers": {
        "edge": {
          "at_version": "1903",
          "browser_version": "44",
          "os_version": "1903",
          "date": "2019-09-27"
        }
      }
    },
    "nvda": {
      "browsers": {
        "chrome": {
          "at_version": "2019.2",
          "browser_version": "77",
          "os_version": "1903",
          "date": "2019-09-27"
        },
        "firefox": {
          "at_version": "2019.2",
          "browser_version": "69",
          "os_version": "1903",
          "date": "2019-09-27"
        }
      }
    },
    "orca": {
      "browsers": {
        "firefox": {
          "at_version": "3.31.4",
          "browser_version": "69",
          "os_version": "Ubuntu 19.04",
          "date": "2019-09-27"
        }
      }
    },
    "talkback": {
      "browsers": {
        "and_chr": {
          "at_version": "7.3.0",
          "browser_version": "77",
          "os_version": "9",
          "date": "2019-09-27"
        }
      }
    },
    "vo_ios": {
      "browsers": {
        "ios_saf": {
          "at_version": "13.1",
          "browser_version": "13.1",
          "os_version": "13.1",
          "date": "2019-09-27"
        }
      }
    },
    "vo_macos": {
      "browsers": {
        "safari": {
          "at_version": "10.14.6",
          "browser_version": "13.0.1",
          "os_version": "10.14.6",
          "date": "2019-09-27"
        }
      }
    },
    "vc_ios": {
      "browsers": {
        "ios_saf": {
          "at_version": "13.1",
          "browser_version": "13.1",
          "os_version": "13.1",
          "date": "2019-09-27"
        }
      }
    }
  }
}

=== BogdanCerovac/a11ysupport.io/data/tests/html_section.json
{
  "title": "HTML section element with no accessible name",
  "description": "This section has no accessible name per HTML AAM 5.15.1 Section and Grouping Element Accessible Name Computation. It will not be mapped to a role and should be considered presentational.",
  "assertions": [
    {
      "feature_id": "html/section_element",
      "feature_assertion_id": "no_role_if_not_named",
      "css_target": "#target",
      "results": {
        "jaws": {
          "browsers": {
            "chrome": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"sample text line 1\"",
                  "result": "pass"
                }
              ]
            },
            "ie": {
              "output": [
                {
                  "command": "next_item",
                  "output": "\"sample text line 1\"",
                  "result": "pass"
                }
              ]
            },
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"sample text line 1\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "narrator": {
          "browsers": {
            "edge": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"sample text line 1\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "nvda": {
          "browsers": {
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "start of target",
                  "output": "\"Sample text line 1\"",
                  "result": "pass"
                }
              ]
            },
            "chrome": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "start of target",
                  "output": "\"Sample text line 1\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "vo_macos": {
          "browsers": {
            "safari": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "start of target",
                  "output": "\"sample text, line 1\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "talkback": {
          "browsers": {
            "and_chr": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"sample text, line 1\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "vo_ios": {
          "browsers": {
            "ios_saf": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"sample text line 1\"",
                  "result": "pass"
                }
              ]
            }
          }
        },
        "orca": {
          "browsers": {
            "firefox": {
              "output": [
                {
                  "command": "next_item",
                  "from": "before target",
                  "to": "target",
                  "output": "\"sample text line 1\"",
                  "result": "pass"
                }
              ]
            }
          }
        }
      }
    }
  ],
  "history": [
    {
      "date": "2018-11-14",
      "message": "Test created"
    },
    {
      "date": "2018-11-14",
      "message": "vo_ios/ios_saf support updated"
    },
    {
      "date": "2019-09-16",
      "message": "add missing results"
    }
  ],
  "versions": {
    "dragon_win": {
      "browsers": {
        "chrome": {
          "at_version": "15.30",
          "browser_version": "76",
          "os_version": "1903",
          "date": "2019-09-16"
        }
      }
    },
    "jaws": {
      "browsers": {
        "chrome": {
          "at_version": "2019.1907.42",
          "browser_version": "76",
          "os_version": "1903",
          "date": "2019-09-16"
        },
        "ie": {
          "at_version": "2019.1907.42",
          "browser_version": "11",
          "os_version": "1903",
          "date": "2019-09-16"
        },
        "firefox": {
          "at_version": "2019.1907.42",
          "browser_version": "69",
          "os_version": "1903",
          "date": "2019-09-16"
        }
      }
    },
    "narrator": {
      "browsers": {
        "edge": {
          "at_version": "1903",
          "browser_version": "44",
          "os_version": "1903",
          "date": "2019-09-16"
        }
      }
    },
    "nvda": {
      "browsers": {
        "chrome": {
          "at_version": "2019.2",
          "browser_version": "76",
          "os_version": "1903",
          "date": "2019-09-16"
        },
        "firefox": {
          "at_version": "2019.2",
          "browser_version": "69",
          "os_version": "1903",
          "date": "2019-09-16"
        }
      }
    },
    "orca": {
      "browsers": {
        "firefox": {
          "at_version": "3.31.4",
          "browser_version": "69",
          "os_version": "Ubuntu 19.04",
          "date": "2019-09-16"
        }
      }
    },
    "talkback": {
      "browsers": {
        "and_chr": {
          "at_version": "7.3.0",
          "browser_version": "76",
          "os_version": "9",
          "date": "2019-09-16"
        }
      }
    },
    "vo_ios": {
      "browsers": {
        "ios_saf": {
          "at_version": "12.4.1",
          "browser_version": "12.4.1",
          "os_version": "12.4.1",
          "date": "2019-09-16"
        }
      }
    },
    "vo_macos": {
      "browsers": {
        "safari": {
          "at_version": "10.14.6",
          "browser_version": "12.1.2",
          "os_version": "10.14.6",
          "date": "2019-09-16"
        }
      }
    }
  }
}
